### ISSUE TITLE
Squad_davinci.raw_data.json

### ISSUE THREAD

**Issue by WSJ0807** [JamesLWang/RAFT#1]
I appreciate your work!

Could you please tell me whether there is Squad_davinci.raw_data.json file?

**Comment by WSJ0807** [comment]
And about the code of raidar? can you share it?  Thanks!

**Comment by JamesLWang** [comment]
Hi @WSJ0807 Thank you for your interest in our work! We are currently in the process of publishing our code and will finalize this repo. by the end of next week (Nov. 10). Will update this thread once the files stated above are added. Thank you for your patience!

**Comment by WSJ0807** [comment]
Got it. Thanks!

**Comment by JamesLWang** [comment]
Hi @WSJ0807. there is no `squad_davinci.raw_data.json` file, as `davinci` logprob was used by Ghosbuster baseline as a feature, but we did not use the `davinci` model in `RAFT` for estimation. 

We have updated the repository with the code we used from `Raidar` described [here](https://github.com/JamesLWang/RAFT?tab=readme-ov-file#adversarial-training).
